name: Merge to Main Workflow

on:
  push:
    branches:
      - main

jobs:
  label_images_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt || pip install boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Execute image labeling script and write to Prod DB
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          python analyze_image.py --output-table ${{ secrets.DYNAMODB_TABLE_PROD }}
      - name: Execute image labeling script and write to Prod DB
        
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE_PROD }}
          BRANCH_NAME: main
        run: |
          python analyze_image.py --output-table ${{ secrets.DYNAMODB_TABLE_PROD }} --images-dir images